# Generated by Django 3.2.9 on 2021-11-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=220, unique=True, verbose_name='Nombre de empleado')),
                ('status', models.CharField(choices=[(None, 'Selecciona estado'), ('Baja ', 'Baja'), ('Baja temporal', 'Baja temporal'), ('Activo', 'Activo')], default='Activo', max_length=25, verbose_name='Estado de empleado')),
                ('emp_num', models.IntegerField(max_length=10, unique=True, verbose_name='Numero de empleado')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
